import argparse
import json
from typing import Any, Dict, List, Optional


class SceneInfo:
    def __init__(self, sceneId: str, className: str, includePath: str):
        self.id = sceneId
        self.className = className
        self.includePath = includePath


class ScenesCreationGenerator:
    GENERATED_CODE_DISCLAIMER = "// This file is generated by the build system. Do not edit manually.\n"
    GENERATED_CODE_HEADER = """
#include <string>
#include <unordered_map>

#include "SDL3/SDL.h"

std::unordered_map<std::string, S2DGameScene*> InitializeScenes(SDL_Renderer* renderer) {
    std::unordered_map<std::string, S2DGameScene*> scenes;\n"""
    GENERATED_CODE_FOOTER = """
    return scenes;
}"""

    def __init__(self, json_path: str, output_path: str):
        self.json_path: str = json_path
        self.output_path: str = output_path  # Path to the output file where the generated code will be saved

        self.json_data: Optional[Dict[Any]] = None
        self.scenes_info: List[SceneInfo] = []

    def readJson(self):
        with open(self.json_path, 'r', encoding='utf-8-sig') as f:
            data = json.load(f)

        self.json_data = data

        if self.json_data is None:
            raise ValueError("JSON data is None. Please check the JSON file.")

        scenes = data.get("scenes", [])
        for scene in scenes:
            scene_id = scene.get("id")
            class_name = scene.get("className")
            include_path = scene.get("includePath")
            if scene_id and class_name and include_path:
                self.scenes_info.append(SceneInfo(scene_id, class_name, include_path))
            else:
                raise ValueError(f"Scene information is incomplete: {scene}, check the JSON file.")

    def generateCode(self):
        with open(self.output_path, 'w') as file:
            file.write(self.GENERATED_CODE_DISCLAIMER)

            for scene_info in self.scenes_info:
                file.write(f'#include "{scene_info.includePath}"\n')

            file.write(self.GENERATED_CODE_HEADER)

            for scene_info in self.scenes_info:
                file.write(f'\tscenes["{scene_info.id}"] = new {scene_info.className}(renderer);\n')

            file.write(self.GENERATED_CODE_FOOTER)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Generate C++ code for scene initialization from a JSON file.")
    parser.add_argument("json_path", help="Path to the input JSON file containing scene information.")
    parser.add_argument("output_path", help="Path to the output C++ file where the generated code will be saved.")

    args = parser.parse_args()

    generator = ScenesCreationGenerator(args.json_path, args.output_path)
    generator.readJson()
    generator.generateCode()